variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - test
  - build
  - publish

test:
  stage: test
  image: maven:3.8.8-eclipse-temurin-17
#  services:
#    - name: docker:25.0.3-dind
#      alias: docker
#  tags:
#    - dind
  script:
      - mvn -s ci_settings.xml help:effective-settings
      - mvn -s ci_settings.xml help:system
      - mvn -f cdoc2-server/ clean verify -s ci_settings.xml -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  artifacts:
    when: always
    reports:
      junit:
        - "**/target/surefire-reports/*.xml"
  cache: 
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .m2/repository

build-components:
  stage: build
  image: maven:3.8.8-eclipse-temurin-17
  
  rules:
    - when: never
  script:
    - mvn -f cdoc2-server/ clean install -DskipTests -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  cache: 
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .m2/repository
  artifacts:
    paths:
      - ./**/target/*.jar

.publish-component: &publish-component
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:v1.22.0-debug
    entrypoint: [""]
  tags:
    - dind
  rules:
    - when: never
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
      /kaniko/executor \
        --context $CI_PROJECT_DIR/cdoc2-server \
        --build-arg NAME=${COMPONENT} \
        --build-arg http_proxy=$http_proxy \
        --build-arg https_proxy=$https_proxy \
        --dockerfile $CI_PROJECT_DIR/cdoc2-server/${COMPONENT}/docker/Dockerfile \
        --destination $DOCKER_IMAGE_NAME:latest \
        --destination $DOCKER_IMAGE_NAME:$CI_COMMIT_REF_SLUG \
        --cache
      else
      /kaniko/executor \
        --context $CI_PROJECT_DIR/cdoc2-server \
        --build-arg NAME=${COMPONENT} \
        --build-arg http_proxy=$http_proxy \
        --build-arg https_proxy=$https_proxy \
        --dockerfile $CI_PROJECT_DIR/cdoc2-server/${COMPONENT}/docker/Dockerfile \
        --destination $DOCKER_IMAGE_NAME:$CI_COMMIT_REF_SLUG \
        --cache
      fi

publish:get-server:
  variables:
    COMPONENT: get-server
    DOCKER_IMAGE_NAME: $DOCKER_REGISTRY/${COMPONENT}
  extends:
    - .publish-component

publish:put-server:
  variables:
    COMPONENT: put-server
    DOCKER_IMAGE_NAME: $DOCKER_REGISTRY/${COMPONENT}
  extends:
    - .publish-component
